### ISSUE TITLE
Include sass-globbing

### ISSUE THREAD

**Issue by trevor-atlas** [Snugug/generator-aurora#11]
Super convenient for large sites with many scss modules, having to add it manually on each site is somewhat annoying.

https://github.com/chriseppstein/sass-globbing

**Comment by Snugug** [comment]
@iamcarrico I'm OK with this despite the [caveat](https://github.com/chriseppstein/sass-globbing#caveats) as it's opt-in via how you write your import statement.

**Comment by iamcarrico** [comment]
... I am not okay with this. Sass-globbing can produce unexpected behaviors and ramifications for the cascade just by renaming of files (re: the caveat). The idea of the generator (and especially the generator-drupal-theme) is to provide some best-practices starting points--- Sass-globbing is not best practices. Which is why it isn't in Compass proper in the first place. 

If developers are already keenly aware of the issues with Sass globbing, then they can install it themselves through the instructions on the repo, we shouldn't add it in by default.

**Comment by Snugug** [comment]
Fair enough.
